from app.schemas.auth import AuthResponse, LoginRequest, RegisterRequest, UserResponse
from app.schemas.groups import (
    GroupMemberResponse,
    GroupMembersResponse,
    TeacherGroupCreateRequest,
    TeacherGroupCreateResponse,
    TeacherGroupUpdateRequest,
    TeacherGroupListItem,
    TeacherInvitationCreateRequest,
    TeacherInvitationResponse,
)
from app.schemas.profile import ProfileInvitationResponse, ProfileResponse
from app.schemas.subjects import SubjectResponse
from app.schemas.teacher import GroupAnalyticsResponse, GroupWeakTopicsResponse
from app.schemas.teacher_tests import (
    TeacherCustomGroupBrief,
    TeacherCustomQuestionInput,
    TeacherCustomQuestionResponse,
    TeacherCustomTestResultsGroupItem,
    TeacherCustomTestResultsResponse,
    TeacherCustomTestResultsStudentItem,
    TeacherCustomTestCreateRequest,
    TeacherCustomTestListItem,
    TeacherCustomTestResponse,
)
from app.schemas.tests import (
    GenerateExamTestRequest,
    GenerateTestRequest,
    GeneratedQuestionPayload,
    GeneratedTestPayload,
    GroupTestSummaryResponse,
    HistoryItemResponse,
    QuestionFeedback,
    QuestionResponse,
    RecommendationResponse,
    ResultResponse,
    StudentProgressResponse,
    SubmitAnswerItem,
    SubmitTestRequest,
    SubmitTestResponse,
    TestResponse,
    TestResultDetailsResponse,
)
from app.schemas.superadmin import (
    BootstrapInviteCreateRequest,
    BootstrapInviteResponse,
    InstitutionCreateRequest,
    InstitutionDetailsResponse,
    InstitutionListItem,
    InstitutionListResponse,
)

__all__ = [
    "AuthResponse",
    "LoginRequest",
    "RegisterRequest",
    "UserResponse",
    "TeacherGroupListItem",
    "TeacherGroupCreateRequest",
    "TeacherGroupCreateResponse",
    "TeacherGroupUpdateRequest",
    "GroupMemberResponse",
    "GroupMembersResponse",
    "TeacherInvitationCreateRequest",
    "TeacherInvitationResponse",
    "ProfileResponse",
    "ProfileInvitationResponse",
    "SubjectResponse",
    "GroupAnalyticsResponse",
    "GroupWeakTopicsResponse",
    "TeacherCustomGroupBrief",
    "TeacherCustomQuestionInput",
    "TeacherCustomQuestionResponse",
    "TeacherCustomTestResultsGroupItem",
    "TeacherCustomTestResultsStudentItem",
    "TeacherCustomTestResultsResponse",
    "TeacherCustomTestCreateRequest",
    "TeacherCustomTestListItem",
    "TeacherCustomTestResponse",
    "GenerateExamTestRequest",
    "GenerateTestRequest",
    "GeneratedQuestionPayload",
    "GeneratedTestPayload",
    "GroupTestSummaryResponse",
    "HistoryItemResponse",
    "QuestionFeedback",
    "QuestionResponse",
    "RecommendationResponse",
    "ResultResponse",
    "StudentProgressResponse",
    "SubmitAnswerItem",
    "SubmitTestRequest",
    "SubmitTestResponse",
    "TestResponse",
    "TestResultDetailsResponse",
    "InstitutionCreateRequest",
    "InstitutionListItem",
    "InstitutionListResponse",
    "InstitutionDetailsResponse",
    "BootstrapInviteCreateRequest",
    "BootstrapInviteResponse",
]
