FACTS = [
    # ===== Tenses / Уақыттар (6 facts) =====
    (
        "easy",
        "Tenses", "Уақыттар",
        "Choose the correct form: She ___ to school every day.",
        "Дұрыс формасын таңдаңыз: She ___ to school every day.",
        ["go", "goes", "going", "gone"],
        ["go", "goes", "going", "gone"],
        1,
        "В Present Simple для третьего лица единственного числа (she) к глаголу добавляется -es: goes.",
        "Present Simple-да үшінші жақ жекеше түрде (she) етістікке -es жалғауы қосылады: goes.",
    ),
    (
        "easy",
        "Tenses", "Уақыттар",
        "Choose the correct form: They ___ football yesterday.",
        "Дұрыс формасын таңдаңыз: They ___ football yesterday.",
        ["play", "played", "playing", "plays"],
        ["play", "played", "playing", "plays"],
        1,
        "Слово 'yesterday' указывает на Past Simple. Правильная форма — played.",
        "'Yesterday' сөзі Past Simple уақытын білдіреді. Дұрыс форма — played.",
    ),
    (
        "medium",
        "Tenses", "Уақыттар",
        "Choose the correct form: I ___ my homework when the phone rang.",
        "Дұрыс формасын таңдаңыз: I ___ my homework when the phone rang.",
        ["did", "was doing", "have done", "do"],
        ["did", "was doing", "have done", "do"],
        1,
        "Past Continuous используется для описания действия, которое происходило в момент другого действия в прошлом.",
        "Past Continuous өткен шақта бір іс-әрекет болып жатқанда басқа іс-әрекеттің болғанын білдіреді.",
    ),
    (
        "medium",
        "Tenses", "Уақыттар",
        "Choose the correct form: By the time we arrived, the movie ___.",
        "Дұрыс формасын таңдаңыз: By the time we arrived, the movie ___.",
        ["started", "has started", "had started", "was starting"],
        ["started", "has started", "had started", "was starting"],
        2,
        "Past Perfect (had started) используется для действия, которое завершилось до другого действия в прошлом.",
        "Past Perfect (had started) өткен шақтағы басқа іс-әрекеттен бұрын аяқталған әрекетті білдіреді.",
    ),
    (
        "hard",
        "Tenses", "Уақыттар",
        "Choose the correct form: This time next week, I ___ on a beach in Thailand.",
        "Дұрыс формасын таңдаңыз: This time next week, I ___ on a beach in Thailand.",
        ["will lie", "will be lying", "am lying", "will have lain"],
        ["will lie", "will be lying", "am lying", "will have lain"],
        1,
        "Future Continuous (will be lying) используется для действия, которое будет происходить в определённый момент в будущем.",
        "Future Continuous (will be lying) болашақта белгілі бір уақытта жүріп жатқан іс-әрекетті білдіреді.",
    ),
    (
        "hard",
        "Tenses", "Уақыттар",
        "Choose the correct form: She ___ three novels by the end of this year.",
        "Дұрыс формасын таңдаңыз: She ___ three novels by the end of this year.",
        ["will write", "will be writing", "will have written", "writes"],
        ["will write", "will be writing", "will have written", "writes"],
        2,
        "Future Perfect (will have written) используется для действия, которое будет завершено к определённому моменту в будущем.",
        "Future Perfect (will have written) болашақта белгілі бір уақытқа дейін аяқталатын іс-әрекетті білдіреді.",
    ),

    # ===== Articles / Артикльдер (6 facts) =====
    (
        "easy",
        "Articles", "Артикльдер",
        "Choose the correct article: ___ sun rises in the east.",
        "Дұрыс артикльді таңдаңыз: ___ sun rises in the east.",
        ["A", "An", "The", "No article"],
        ["A", "An", "The", "No article"],
        2,
        "Определённый артикль 'the' используется с уникальными объектами: the sun.",
        "'The' анықтауыш артикль бірегей нысандармен қолданылады: the sun.",
    ),
    (
        "easy",
        "Articles", "Артикльдер",
        "Choose the correct article: She is ___ honest person.",
        "Дұрыс артикльді таңдаңыз: She is ___ honest person.",
        ["a", "an", "the", "no article"],
        ["a", "an", "the", "no article"],
        1,
        "Артикль 'an' используется перед словами, начинающимися с гласного звука. 'Honest' начинается с гласного звука /ɒ/.",
        "'An' артикль дауысты дыбыстан басталатын сөздердің алдында қолданылады. 'Honest' сөзі /ɒ/ дауысты дыбысынан басталады.",
    ),
    (
        "medium",
        "Articles", "Артикльдер",
        "Choose the correct article: He wants to be ___ engineer when he grows up.",
        "Дұрыс артикльді таңдаңыз: He wants to be ___ engineer when he grows up.",
        ["a", "an", "the", "no article"],
        ["a", "an", "the", "no article"],
        1,
        "'An' используется перед словами, начинающимися с гласного звука. 'Engineer' начинается с /e/.",
        "'An' дауысты дыбыстан басталатын сөздердің алдында қолданылады. 'Engineer' сөзі /e/ дыбысынан басталады.",
    ),
    (
        "medium",
        "Articles", "Артикльдер",
        "Choose the correct option: I usually have ___ breakfast at 8 a.m.",
        "Дұрыс нұсқаны таңдаңыз: I usually have ___ breakfast at 8 a.m.",
        ["a", "an", "the", "no article"],
        ["a", "an", "the", "no article"],
        3,
        "Перед названиями приёмов пищи (breakfast, lunch, dinner) артикль не используется.",
        "Тамақ атаулары алдында (breakfast, lunch, dinner) артикль қолданылмайды.",
    ),
    (
        "hard",
        "Articles", "Артикльдер",
        "Choose the correct article: ___ Nile is the longest river in Africa.",
        "Дұрыс артикльді таңдаңыз: ___ Nile is the longest river in Africa.",
        ["A", "An", "The", "No article"],
        ["A", "An", "The", "No article"],
        2,
        "Определённый артикль 'the' используется с названиями рек: the Nile.",
        "'The' анықтауыш артикль өзен атауларымен қолданылады: the Nile.",
    ),
    (
        "hard",
        "Articles", "Артикльдер",
        "Choose the correct option: She plays ___ piano beautifully.",
        "Дұрыс нұсқаны таңдаңыз: She plays ___ piano beautifully.",
        ["a", "an", "the", "no article"],
        ["a", "an", "the", "no article"],
        2,
        "Перед названиями музыкальных инструментов используется артикль 'the': play the piano.",
        "Музыкалық аспаптар атауларының алдында 'the' артикль қолданылады: play the piano.",
    ),

    # ===== Prepositions / Предлогтар (5 facts) =====
    (
        "easy",
        "Prepositions", "Предлогтар",
        "Choose the correct preposition: The meeting is ___ Monday.",
        "Дұрыс предлогты таңдаңыз: The meeting is ___ Monday.",
        ["in", "on", "at", "by"],
        ["in", "on", "at", "by"],
        1,
        "Предлог 'on' используется с днями недели: on Monday.",
        "'On' предлогы апта күндерімен қолданылады: on Monday.",
    ),
    (
        "easy",
        "Prepositions", "Предлогтар",
        "Choose the correct preposition: She arrived ___ 5 o'clock.",
        "Дұрыс предлогты таңдаңыз: She arrived ___ 5 o'clock.",
        ["in", "on", "at", "for"],
        ["in", "on", "at", "for"],
        2,
        "Предлог 'at' используется с точным временем: at 5 o'clock.",
        "'At' предлогы нақты уақытпен қолданылады: at 5 o'clock.",
    ),
    (
        "medium",
        "Prepositions", "Предлогтар",
        "Choose the correct preposition: He is interested ___ science.",
        "Дұрыс предлогты таңдаңыз: He is interested ___ science.",
        ["on", "at", "in", "for"],
        ["on", "at", "in", "for"],
        2,
        "Устойчивое выражение: interested in (интересоваться чем-либо).",
        "Тұрақты тіркес: interested in (бір нәрсеге қызығу).",
    ),
    (
        "medium",
        "Prepositions", "Предлогтар",
        "Choose the correct preposition: She apologized ___ being late.",
        "Дұрыс предлогты таңдаңыз: She apologized ___ being late.",
        ["for", "about", "on", "to"],
        ["for", "about", "on", "to"],
        0,
        "Устойчивое выражение: apologize for (извиняться за что-либо).",
        "Тұрақты тіркес: apologize for (бір нәрсе үшін кешірім сұрау).",
    ),
    (
        "hard",
        "Prepositions", "Предлогтар",
        "Choose the correct preposition: The book was written ___ Mark Twain.",
        "Дұрыс предлогты таңдаңыз: The book was written ___ Mark Twain.",
        ["from", "with", "by", "of"],
        ["from", "with", "by", "of"],
        2,
        "В пассивном залоге исполнитель действия вводится предлогом 'by': written by Mark Twain.",
        "Ырықсыз етісте іс-әрекетті орындаушы 'by' предлогымен енгізіледі: written by Mark Twain.",
    ),

    # ===== Modal verbs / Модал етістіктер (6 facts) =====
    (
        "easy",
        "Modal verbs", "Модал етістіктер",
        "Choose the correct modal verb: You ___ wear a seatbelt in the car. It's the law.",
        "Дұрыс модал етістікті таңдаңыз: You ___ wear a seatbelt in the car. It's the law.",
        ["can", "must", "might", "could"],
        ["can", "must", "might", "could"],
        1,
        "'Must' выражает обязанность или закон. Пристёгивать ремень — требование закона.",
        "'Must' міндеттілікті немесе заңды білдіреді. Белбеуді тағу — заң талабы.",
    ),
    (
        "easy",
        "Modal verbs", "Модал етістіктер",
        "Choose the correct modal verb: ___ I borrow your pen, please?",
        "Дұрыс модал етістікті таңдаңыз: ___ I borrow your pen, please?",
        ["Must", "Should", "Can", "Will"],
        ["Must", "Should", "Can", "Will"],
        2,
        "'Can' используется для вежливой просьбы.",
        "'Can' сыпайы өтініш білдіру үшін қолданылады.",
    ),
    (
        "medium",
        "Modal verbs", "Модал етістіктер",
        "Choose the correct modal verb: You ___ see a doctor. You look very ill.",
        "Дұрыс модал етістікті таңдаңыз: You ___ see a doctor. You look very ill.",
        ["should", "might", "can", "would"],
        ["should", "might", "can", "would"],
        0,
        "'Should' используется для рекомендации или совета.",
        "'Should' кеңес немесе ұсыныс білдіру үшін қолданылады.",
    ),
    (
        "medium",
        "Modal verbs", "Модал етістіктер",
        "Choose the correct modal verb: She ___ speak French when she was five.",
        "Дұрыс модал етістікті таңдаңыз: She ___ speak French when she was five.",
        ["can", "could", "may", "must"],
        ["can", "could", "may", "must"],
        1,
        "'Could' используется для обозначения способности в прошлом.",
        "'Could' өткен шақтағы қабілетті білдіру үшін қолданылады.",
    ),
    (
        "hard",
        "Modal verbs", "Модал етістіктер",
        "Choose the correct form: He ___ have left already; his car is not here.",
        "Дұрыс формасын таңдаңыз: He ___ have left already; his car is not here.",
        ["can", "must", "should", "would"],
        ["can", "must", "should", "would"],
        1,
        "'Must have + V3' выражает уверенное предположение о прошлом.",
        "'Must have + V3' өткен шақ туралы сенімді болжамды білдіреді.",
    ),
    (
        "hard",
        "Modal verbs", "Модал етістіктер",
        "Choose the correct form: You ___ have told me earlier! Now it's too late.",
        "Дұрыс формасын таңдаңыз: You ___ have told me earlier! Now it's too late.",
        ["must", "could", "should", "would"],
        ["must", "could", "should", "would"],
        2,
        "'Should have + V3' выражает сожаление о том, что действие не было совершено в прошлом.",
        "'Should have + V3' өткен шақта жасалмаған іс-әрекетке өкіну мағынасын білдіреді.",
    ),

    # ===== Conditionals / Шартты сөйлемдер (5 facts) =====
    (
        "easy",
        "Conditionals", "Шартты сөйлемдер",
        "Choose the correct form: If it ___, we will stay at home.",
        "Дұрыс формасын таңдаңыз: If it ___, we will stay at home.",
        ["rains", "will rain", "rained", "would rain"],
        ["rains", "will rain", "rained", "would rain"],
        0,
        "В условных предложениях первого типа (First Conditional) в части с 'if' используется Present Simple.",
        "Бірінші типтегі шартты сөйлемдерде (First Conditional) 'if' бөлігінде Present Simple қолданылады.",
    ),
    (
        "medium",
        "Conditionals", "Шартты сөйлемдер",
        "Choose the correct form: If I ___ you, I would apologize.",
        "Дұрыс формасын таңдаңыз: If I ___ you, I would apologize.",
        ["am", "was", "were", "be"],
        ["am", "was", "were", "be"],
        2,
        "В условных предложениях второго типа (Second Conditional) после 'if' используется 'were' для всех лиц.",
        "Екінші типтегі шартты сөйлемдерде (Second Conditional) 'if' кейін барлық жақтар үшін 'were' қолданылады.",
    ),
    (
        "medium",
        "Conditionals", "Шартты сөйлемдер",
        "Choose the correct form: If she studied harder, she ___ better grades.",
        "Дұрыс формасын таңдаңыз: If she studied harder, she ___ better grades.",
        ["will get", "would get", "gets", "got"],
        ["will get", "would get", "gets", "got"],
        1,
        "В условных предложениях второго типа главная часть содержит 'would + infinitive'.",
        "Екінші типтегі шартты сөйлемдерде негізгі бөлімде 'would + infinitive' қолданылады.",
    ),
    (
        "hard",
        "Conditionals", "Шартты сөйлемдер",
        "Choose the correct form: If they ___ the train, they would have arrived on time.",
        "Дұрыс формасын таңдаңыз: If they ___ the train, they would have arrived on time.",
        ["caught", "had caught", "have caught", "would catch"],
        ["caught", "had caught", "have caught", "would catch"],
        1,
        "В условных предложениях третьего типа (Third Conditional) в части с 'if' используется Past Perfect.",
        "Үшінші типтегі шартты сөйлемдерде (Third Conditional) 'if' бөлігінде Past Perfect қолданылады.",
    ),
    (
        "hard",
        "Conditionals", "Шартты сөйлемдер",
        "Choose the correct form: If I had known about the meeting, I ___ attended.",
        "Дұрыс формасын таңдаңыз: If I had known about the meeting, I ___ attended.",
        ["will have", "would have", "had", "would"],
        ["will have", "would have", "had", "would"],
        1,
        "В условных предложениях третьего типа главная часть содержит 'would have + V3'.",
        "Үшінші типтегі шартты сөйлемдерде негізгі бөлімде 'would have + V3' қолданылады.",
    ),

    # ===== Reported speech / Төлеу сөз (6 facts) =====
    (
        "easy",
        "Reported speech", "Төлеу сөз",
        "Convert to reported speech: He said, 'I am tired.' → He said that he ___ tired.",
        "Төлеу сөзге аударыңыз: He said, 'I am tired.' → He said that he ___ tired.",
        ["is", "was", "am", "were"],
        ["is", "was", "am", "were"],
        1,
        "При переводе в косвенную речь 'am' меняется на 'was' (сдвиг времени).",
        "Төлеу сөзге ауыстырғанда 'am' 'was' болып өзгереді (уақыт ауысуы).",
    ),
    (
        "easy",
        "Reported speech", "Төлеу сөз",
        "Convert to reported speech: She said, 'I like chocolate.' → She said that she ___ chocolate.",
        "Төлеу сөзге аударыңыз: She said, 'I like chocolate.' → She said that she ___ chocolate.",
        ["likes", "liked", "like", "liking"],
        ["likes", "liked", "like", "liking"],
        1,
        "При переводе в косвенную речь Present Simple меняется на Past Simple: like → liked.",
        "Төлеу сөзге ауыстырғанда Present Simple Past Simple-ға ауысады: like → liked.",
    ),
    (
        "medium",
        "Reported speech", "Төлеу сөз",
        "Convert to reported speech: 'I will help you,' he said. → He said that he ___ help me.",
        "Төлеу сөзге аударыңыз: 'I will help you,' he said. → He said that he ___ help me.",
        ["will", "would", "shall", "can"],
        ["will", "would", "shall", "can"],
        1,
        "При переводе в косвенную речь 'will' меняется на 'would'.",
        "Төлеу сөзге ауыстырғанда 'will' 'would' болып өзгереді.",
    ),
    (
        "medium",
        "Reported speech", "Төлеу сөз",
        "Convert to reported speech: 'Where do you live?' she asked. → She asked me where I ___.",
        "Төлеу сөзге аударыңыз: 'Where do you live?' she asked. → She asked me where I ___.",
        ["live", "lived", "do live", "living"],
        ["live", "lived", "do live", "living"],
        1,
        "В косвенном вопросе используется прямой порядок слов и сдвиг времени: live → lived.",
        "Жанама сұрақта тура сөз тәртібі және уақыт ауысуы қолданылады: live → lived.",
    ),
    (
        "hard",
        "Reported speech", "Төлеу сөз",
        "Convert to reported speech: 'Don't touch the wire!' he said. → He warned me ___ the wire.",
        "Төлеу сөзге аударыңыз: 'Don't touch the wire!' he said. → He warned me ___ the wire.",
        ["to not touch", "not to touch", "don't touch", "not touching"],
        ["to not touch", "not to touch", "don't touch", "not touching"],
        1,
        "При переводе отрицательного повелительного наклонения в косвенную речь используется 'not to + infinitive'.",
        "Болымсыз бұйрық рай төлеу сөзге ауысқанда 'not to + infinitive' қолданылады.",
    ),
    (
        "hard",
        "Reported speech", "Төлеу сөз",
        "Convert to reported speech: 'I have never been to Japan,' she said. → She said she ___ never been to Japan.",
        "Төлеу сөзге аударыңыз: 'I have never been to Japan,' she said. → She said she ___ never been to Japan.",
        ["has", "had", "have", "having"],
        ["has", "had", "have", "having"],
        1,
        "При переводе в косвенную речь Present Perfect (have been) меняется на Past Perfect (had been).",
        "Төлеу сөзге ауыстырғанда Present Perfect (have been) Past Perfect (had been) болып өзгереді.",
    ),

    # ===== Vocabulary / Сөздік қор (6 facts) =====
    (
        "easy",
        "Vocabulary", "Сөздік қор",
        "Choose the correct word: A person who writes books is called ___.",
        "Дұрыс сөзді таңдаңыз: Кітап жазатын адам ___ деп аталады.",
        ["a reader", "an author", "a librarian", "a publisher"],
        ["a reader", "an author", "a librarian", "a publisher"],
        1,
        "Человек, который пишет книги, — это автор (author).",
        "Кітап жазатын адам — автор (author).",
    ),
    (
        "medium",
        "Vocabulary", "Сөздік қор",
        "Choose the correct word: I couldn't sleep because of the ___ noise from the construction site.",
        "Дұрыс сөзді таңдаңыз: Құрылыс алаңындағы ___ шудан ұйықтай алмадым.",
        ["quiet", "deafening", "silent", "soft"],
        ["quiet", "deafening", "silent", "soft"],
        1,
        "'Deafening' означает оглушительный — подходит для описания сильного шума.",
        "'Deafening' — құлақ тұндыратын, қатты шуды сипаттау үшін қолданылады.",
    ),
    (
        "medium",
        "Vocabulary", "Сөздік қор",
        "Choose the synonym of 'enormous':",
        "'Enormous' сөзінің синонимін таңдаңыз:",
        ["tiny", "huge", "average", "narrow"],
        ["tiny", "huge", "average", "narrow"],
        1,
        "'Enormous' означает 'огромный'. Синоним — 'huge'.",
        "'Enormous' — 'орасан зор' дегенді білдіреді. Синонимі — 'huge'.",
    ),
    (
        "hard",
        "Vocabulary", "Сөздік қор",
        "Choose the correct word: The politician tried to ___ the scandal by blaming his assistant.",
        "Дұрыс сөзді таңдаңыз: Саясаткер жәрдемшісін кінәлай отырып, скандалды ___ тырысты.",
        ["cover up", "make up", "bring up", "set up"],
        ["cover up", "make up", "bring up", "set up"],
        0,
        "'Cover up' означает 'скрыть, замять' (что-то неприятное).",
        "'Cover up' — 'жасыру, бүркемелеу' (жағымсыз нәрсені) дегенді білдіреді.",
    ),
    (
        "hard",
        "Vocabulary", "Сөздік қор",
        "Choose the correct word: Her ___ response surprised everyone; she usually takes a long time to decide.",
        "Дұрыс сөзді таңдаңыз: Оның ___ жауабы бәрін таңдандырды; ол әдетте шешім қабылдауға ұзақ уақыт кетіреді.",
        ["reluctant", "prompt", "gradual", "hesitant"],
        ["reluctant", "prompt", "gradual", "hesitant"],
        1,
        "'Prompt' означает 'быстрый, незамедлительный' — контрастирует с обычно долгим принятием решений.",
        "'Prompt' — 'жылдам, кідіріссіз' дегенді білдіреді — әдеттегі ұзақ шешім қабылдаумен салыстырылады.",
    ),

    # ===== Passive voice / Ырықсыз етіс (6 facts) =====
    (
        "easy",
        "Passive voice", "Ырықсыз етіс",
        "Choose the correct passive form: The cake ___ by my grandmother.",
        "Дұрыс ырықсыз етіс формасын таңдаңыз: The cake ___ by my grandmother.",
        ["baked", "was baked", "is baking", "bakes"],
        ["baked", "was baked", "is baking", "bakes"],
        1,
        "В пассивном залоге (Past Simple) используется 'was/were + V3': was baked.",
        "Ырықсыз етісте (Past Simple) 'was/were + V3' қолданылады: was baked.",
    ),
    (
        "easy",
        "Passive voice", "Ырықсыз етіс",
        "Choose the correct passive form: English ___ in many countries.",
        "Дұрыс ырықсыз етіс формасын таңдаңыз: English ___ in many countries.",
        ["speaks", "is spoken", "speaking", "spoke"],
        ["speaks", "is spoken", "speaking", "spoke"],
        1,
        "В пассивном залоге (Present Simple) используется 'is/are + V3': is spoken.",
        "Ырықсыз етісте (Present Simple) 'is/are + V3' қолданылады: is spoken.",
    ),
    (
        "medium",
        "Passive voice", "Ырықсыз етіс",
        "Choose the correct passive form: The new hospital ___ next year.",
        "Дұрыс ырықсыз етіс формасын таңдаңыз: The new hospital ___ next year.",
        ["will build", "will be built", "is building", "builds"],
        ["will build", "will be built", "is building", "builds"],
        1,
        "В пассивном залоге (Future Simple) используется 'will be + V3': will be built.",
        "Ырықсыз етісте (Future Simple) 'will be + V3' қолданылады: will be built.",
    ),
    (
        "medium",
        "Passive voice", "Ырықсыз етіс",
        "Choose the correct passive form: The letter ___ right now.",
        "Дұрыс ырықсыз етіс формасын таңдаңыз: The letter ___ right now.",
        ["is writing", "is being written", "has written", "was written"],
        ["is writing", "is being written", "has written", "was written"],
        1,
        "В пассивном залоге (Present Continuous) используется 'is/are being + V3': is being written.",
        "Ырықсыз етісте (Present Continuous) 'is/are being + V3' қолданылады: is being written.",
    ),
    (
        "hard",
        "Passive voice", "Ырықсыз етіс",
        "Choose the correct passive form: The report ___ by the time the manager arrived.",
        "Дұрыс ырықсыз етіс формасын таңдаңыз: The report ___ by the time the manager arrived.",
        ["was completed", "had been completed", "has been completed", "completed"],
        ["was completed", "had been completed", "has been completed", "completed"],
        1,
        "В пассивном залоге (Past Perfect) используется 'had been + V3': had been completed.",
        "Ырықсыз етісте (Past Perfect) 'had been + V3' қолданылады: had been completed.",
    ),
    (
        "hard",
        "Passive voice", "Ырықсыз етіс",
        "Choose the correct passive form: Three suspects ___ so far.",
        "Дұрыс ырықсыз етіс формасын таңдаңыз: Three suspects ___ so far.",
        ["arrested", "have been arrested", "were arrested", "are arresting"],
        ["arrested", "have been arrested", "were arrested", "are arresting"],
        1,
        "В пассивном залоге (Present Perfect) используется 'have/has been + V3'. 'So far' указывает на Present Perfect.",
        "Ырықсыз етісте (Present Perfect) 'have/has been + V3' қолданылады. 'So far' Present Perfect-ке нұсқайды.",
    ),

    # ===== Phrasal verbs / Фразалық етістіктер (5 facts) =====
    (
        "easy",
        "Phrasal verbs", "Фразалық етістіктер",
        "Choose the correct phrasal verb: Please ___ your shoes before entering the house.",
        "Дұрыс фразалық етістікті таңдаңыз: Үйге кірер алдында аяқ киіміңізді ___.",
        ["take off", "take on", "take up", "take over"],
        ["take off", "take on", "take up", "take over"],
        0,
        "'Take off' означает 'снять' (одежду, обувь).",
        "'Take off' — 'шешу' (киім, аяқ киім) дегенді білдіреді.",
    ),
    (
        "medium",
        "Phrasal verbs", "Фразалық етістіктер",
        "Choose the correct phrasal verb: I need to ___ this word in the dictionary.",
        "Дұрыс фразалық етістікті таңдаңыз: Бұл сөзді сөздіктен ___ керек.",
        ["look up", "look after", "look out", "look into"],
        ["look up", "look after", "look out", "look into"],
        0,
        "'Look up' означает 'искать информацию' (в словаре, справочнике).",
        "'Look up' — 'ақпарат іздеу' (сөздіктен, анықтамалықтан) дегенді білдіреді.",
    ),
    (
        "medium",
        "Phrasal verbs", "Фразалық етістіктер",
        "Choose the correct phrasal verb: We had to ___ the meeting because of the storm.",
        "Дұрыс фразалық етістікті таңдаңыз: Дауыл салдарынан жиналысты ___ тура келді.",
        ["call off", "call up", "call on", "call for"],
        ["call off", "call up", "call on", "call for"],
        0,
        "'Call off' означает 'отменить' (мероприятие, встречу).",
        "'Call off' — 'бас тарту, тоқтату' (іс-шара, кездесу) дегенді білдіреді.",
    ),
    (
        "hard",
        "Phrasal verbs", "Фразалық етістіктер",
        "Choose the correct phrasal verb: Scientists are trying to ___ a cure for the disease.",
        "Дұрыс фразалық етістікті таңдаңыз: Ғалымдар ауруға шипа ___.",
        ["come up with", "come across", "come down with", "come into"],
        ["come up with", "come across", "come down with", "come into"],
        0,
        "'Come up with' означает 'придумать, найти' (решение, идею).",
        "'Come up with' — 'ойлап табу, табу' (шешім, идея) дегенді білдіреді.",
    ),
    (
        "hard",
        "Phrasal verbs", "Фразалық етістіктер",
        "Choose the correct phrasal verb: He ___ his father; they look exactly alike.",
        "Дұрыс фразалық етістікті таңдаңыз: Ол әкесіне ___; олар бір-біріне ұқсас.",
        ["takes after", "takes over", "takes up", "takes in"],
        ["takes after", "takes over", "takes up", "takes in"],
        0,
        "'Take after' означает 'быть похожим на кого-то' (о родственниках).",
        "'Take after' — 'біреуге ұқсау' (туыстар туралы) дегенді білдіреді.",
    ),

    # ===== Comparatives / Салыстырмалы дәреже (5 facts) =====
    (
        "easy",
        "Comparatives", "Салыстырмалы дәреже",
        "Choose the correct form: This book is ___ than that one.",
        "Дұрыс формасын таңдаңыз: Бұл кітап анаусынан ___.",
        ["interesting", "more interesting", "most interesting", "interestinger"],
        ["interesting", "more interesting", "most interesting", "interestinger"],
        1,
        "Для многосложных прилагательных сравнительная степень образуется с помощью 'more': more interesting.",
        "Көп буынды сын есімдердің салыстырмалы шырайы 'more' арқылы жасалады: more interesting.",
    ),
    (
        "easy",
        "Comparatives", "Салыстырмалы дәреже",
        "Choose the correct form: My sister is ___ than me.",
        "Дұрыс формасын таңдаңыз: Менің әпкем менен ___.",
        ["tall", "taller", "tallest", "more tall"],
        ["tall", "taller", "tallest", "more tall"],
        1,
        "Для односложных прилагательных сравнительная степень образуется добавлением -er: taller.",
        "Бір буынды сын есімдерде салыстырмалы шырай -er жалғауымен жасалады: taller.",
    ),
    (
        "medium",
        "Comparatives", "Салыстырмалы дәреже",
        "Choose the correct form: This is ___ movie I have ever seen.",
        "Дұрыс формасын таңдаңыз: Бұл менің көрген ___ фильмім.",
        ["the best", "the goodest", "better", "more good"],
        ["the best", "the goodest", "better", "more good"],
        0,
        "Превосходная степень от 'good' — 'the best' (неправильная форма).",
        "'Good' сөзінің күшейтпелі шырайы — 'the best' (бұрыс форма).",
    ),
    (
        "hard",
        "Comparatives", "Салыстырмалы дәреже",
        "Choose the correct form: The ___ you study, the ___ your results will be.",
        "Дұрыс формасын таңдаңыз: ___ көп оқысаңыз, нәтижелеріңіз ___ жақсы болады.",
        ["more / better", "most / best", "more / more good", "much / good"],
        ["more / better", "most / best", "more / more good", "much / good"],
        0,
        "Конструкция 'the + comparative, the + comparative': The more … the better.",
        "'The + салыстырмалы шырай, the + салыстырмалы шырай' құрылымы: The more … the better.",
    ),
    (
        "hard",
        "Comparatives", "Салыстырмалы дәреже",
        "Choose the correct form: This task is ___ difficult than the previous one.",
        "Дұрыс формасын таңдаңыз: Бұл тапсырма алдыңғыдан ___ қиын.",
        ["much more", "much", "very more", "more much"],
        ["much more", "much", "very more", "more much"],
        0,
        "'Much more' используется для усиления сравнительной степени многосложных прилагательных.",
        "'Much more' көп буынды сын есімдердің салыстырмалы шырайын күшейту үшін қолданылады.",
    ),
]
