// AUTO-GENERATED by scripts/extract-palette.ts
// If logo file is replaced, re-run: npm run extract-palette


export const brandPalette = [
  "#6E6EF2",
  "#C6C6F2",
  "#CFA44E",
  "#B0B0F2",
  "#1E1C2E",
  "#DCDCFF",
  "#8484F2"
] as const;

export const brandColors = {
  primary: brandPalette[0],
  secondary: brandPalette[1],
  accent: brandPalette[2],
  paper: brandPalette[3],
  ink: brandPalette[4],
  mist: brandPalette[5],
  glow: brandPalette[6],
} as const;

export const brandMeta = {
  generatedAt: "2026-02-25T08:52:16.171Z",
  source: "frontend/public/assets/logo/logo.png",
  fallbackUsed: false,
} as const;
